export const products = [
  {
    img: "../homework.1,2,3,4,5,6/img/photo-mousse.jpg",
    skinType: "для нормальной кожи",
    title: "Увлажняющий мусс",
    description: "Глубоко увлажняют кожу лица, оставляя её мягкой и гладкой.",
    composition: "Состав:",
    item1: "активные натуральные комплексы",
    item2: "витамины С, А, РР, В И Е",
    item3: "солнцезащитные компоненты",
    priceText: "Цена:",
    price: 1375,
    currency: "₽",
  },
  {
    img: "../homework.1,2,3,4,5,6/img/photo-mask.jpg",
    skinType: "для нормальной кожи",
    title: "Увлажняющая маска",
    description: "Способствует удерживанию влаги в верхних слоях кожи.",
    composition: "Состав:",
    item1: "воски",
    item2: "минералы",
    item3: "масла",
    priceText: "Цена:",
    price: 3500,
    currency: "₽",
  },
  {
    img: "../homework.1,2,3,4,5,6/img/photo-gel.jpg",
    skinType: "для нормальной кожи",
    title: "Гель для умывания",
    description: " Интенсивно очищает, не повреждает защитный барьер кожи.",
    composition: "Состав:",
    item1: "минералы",
    item2: "витамины С, А, РР, В И Е",
    item3: "солнцезащитные компоненты",
    priceText: "Цена:",
    price: 1650,
    currency: "₽",
  },
  {
    img: "../homework.1,2,3,4,5,6/img/photo-set-1.jpg",
    skinType: "для нормальной кожи",
    title: "Подарочный набор №1",
    description: "Набор, состоящий из увлажняющего крема и маски.",
    composition: "Состав:",
    item1: "воски",
    item2: "минералы",
    item3: "масла",
    priceText: "Цена:",
    price: 4750,
    currency: "₽",
  },
  {
    img: "../homework.1,2,3,4,5,6/img/photo-set-5.jpg",
    skinType: "для нормальной кожи",
    title: "Подарочный набор №5",
    description:
      " Весь набор средств Invisible symphony, крем, маска, мусс и гель для умывания.",
    composition: "Состав:",
    item1: "воски",
    item2: "минералы",
    item3: "масла",
    priceText: "Цена:",
    price: 7520,
    currency: "₽",
  },
];
